--- 
- 
  become: true
  hosts: localhost
  tasks: 
    - 
      file: 
        group: "{{ ansible_user }}"
        mode: "0775"
        owner: "{{ ansible_user }}"
        path: "/var/www/{{ domain }}"
        state: directory
      name: "create www directory"
    - 
      file: 
        path: /etc/nginx/sites-enabled/default
        state: absent
      name: "delete default nginx site"
      notify: "restart nginx"
    - 
      name: "copy nginx site.conf"
      notify: "restart nginx"
      template: 
        dest: "/etc/nginx/sites-enabled/{{ domain }}"
        group: root
        mode: "0644"
        owner: root
        src: site.conf.j2

